version: 2.1
jobs:
  build:
    docker:
      - image: circleci/node:9.6.1
    steps:
      - slack/notify:
          color: '#42e2f4'
          message: Build Successful
orbs:
  node: circleci/node@3.0.0
  slack: circleci/slack@3.4.2
workflows:
  node-tests:
    jobs:
      - node/test
      - build
